#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Comet Policy Patcher for macOS (LaunchAgent Method)
# -----------------------------------------------------------------------------
# This script creates a LaunchAgent that automatically patches Comet's
# "Local State" file to allow extensions on perplexity.ai domains.
#
# Unlike the old method, this does NOT require a custom shortcut. The patch
# is applied automatically in the background, similar to the Windows method.
#
# How it works:
# 1. Creates a LaunchAgent plist that runs on login
# 2. The agent monitors and patches the Local State file before Comet launches
# 3. Launch Comet normally - no custom shortcut needed!
#
# Notes:
# - No admin privileges required
# - Built-in tools only (bash, launchctl)
# - Logs are written to: ~/Library/Logs/Comet-Policy-Patcher.log
# -----------------------------------------------------------------------------

set -euo pipefail

# ----------------------------- Config & Paths --------------------------------
AGENT_LABEL="app.cplx.comet-policy-patcher"
AGENT_PLIST="${HOME}/Library/LaunchAgents/${AGENT_LABEL}.plist"
PATCHER_SCRIPT="${HOME}/Library/Application Support/Complexity/comet-patcher.sh"
LOG_FILE="${HOME}/Library/Logs/Comet-Policy-Patcher.log"
USER_DATA_DIR="${HOME}/Library/Application Support/Comet"
LOCAL_STATE="${USER_DATA_DIR}/Local State"

# ----------------------------- Pretty Printers --------------------------------
msg()  { printf "[Installer] %s\n" "$*"; }
ok()   { printf "✔ %s\n" "$*"; }
warn() { printf "⚠ %s\n" "$*"; }
err()  { printf "✖ %s\n" "$*"; }

# ------------------------------ Intro Banner ----------------------------------
print_intro() {
  printf "\n"
  printf "============================================================\n"
  printf "   Comet Policy Patcher for macOS (New Method)\n"
  printf "============================================================\n\n"
  printf "This installer creates a background service (LaunchAgent) that\n"
  printf "automatically patches Comet to allow extensions on perplexity.ai.\n\n"
  printf "Unlike the old method, you DON'T need a custom shortcut!\n"
  printf "Just launch Comet normally after installation.\n\n"
  printf "============================================================\n\n"
}

# ------------------------ Create Patcher Script -------------------------------
create_patcher_script() {
  msg "Creating patcher script..."
  
  mkdir -p "$(dirname "$PATCHER_SCRIPT")"
  mkdir -p "$(dirname "$LOG_FILE")"
  
  cat > "$PATCHER_SCRIPT" <<'PATCHER'
#!/usr/bin/env bash
# Auto-generated by Comet Policy Patcher installer
set -euo pipefail

USER_DATA_DIR="${HOME}/Library/Application Support/Comet"
LOCAL_STATE="${USER_DATA_DIR}/Local State"
LOG_FILE="${HOME}/Library/Logs/Comet-Policy-Patcher.log"
BACKUP="${LOCAL_STATE}.cplx.bak"

log() {
  printf "[%s] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >> "$LOG_FILE"
}

ensure_dirs() {
  mkdir -p "${USER_DATA_DIR}"
  mkdir -p "$(dirname "$LOG_FILE")"
}

backup_local_state() {
  if [[ -f "$LOCAL_STATE" ]]; then
    cp -f "$LOCAL_STATE" "$BACKUP" 2>/dev/null || true
  else
    # Create minimal JSON if file doesn't exist
    printf '{}' > "$LOCAL_STATE"
  fi
}

verify_true() {
  grep -Eq '"Allow-external-extensions-scripting-on-NTP"[[:space:]]*:[[:space:]]*true' "$LOCAL_STATE" 2>/dev/null
}

patch_file() {
  if [[ ! -f "$LOCAL_STATE" ]]; then
    log "Local State file doesn't exist yet, skipping patch."
    return 0
  fi
  
  local before after
  before="$(grep -Eo '"Allow-external-extensions-scripting-on-NTP"[[:space:]]*:[[:space:]]*(true|false)' "$LOCAL_STATE" 2>/dev/null || echo "not found")"
  
  # Check if already true
  if verify_true; then
    log "Already patched (key is true), no action needed."
    return 0
  fi
  
  # Patch: false -> true
  /usr/bin/sed -E -i '' \
    's/"Allow-external-extensions-scripting-on-NTP"[[:space:]]*:[[:space:]]*false/"Allow-external-extensions-scripting-on-NTP": true/g' \
    "$LOCAL_STATE" 2>/dev/null || {
      log "Failed to patch file with sed"
      return 1
    }
  
  after="$(grep -Eo '"Allow-external-extensions-scripting-on-NTP"[[:space:]]*:[[:space:]]*(true|false)' "$LOCAL_STATE" 2>/dev/null || echo "not found")"
  log "Patched: Before=${before} -> After=${after}"
}

main() {
  log "=== Comet Policy Patcher triggered ==="
  ensure_dirs
  
  # Wait a moment for Comet to finish writing the file
  # This ensures we don't patch while Comet is still writing
  sleep 3
  
  backup_local_state
  patch_file
  
  log "=== Patch cycle complete ==="
}

main "$@"
PATCHER
  
  chmod +x "$PATCHER_SCRIPT"
  ok "Patcher script created at: $PATCHER_SCRIPT"
}

# ----------------------- Create LaunchAgent Plist -----------------------------
create_launch_agent() {
  msg "Creating LaunchAgent..."
  
  mkdir -p "$(dirname "$AGENT_PLIST")"
  
  cat > "$AGENT_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${AGENT_LABEL}</string>
  
  <key>ProgramArguments</key>
  <array>
    <string>${PATCHER_SCRIPT}</string>
  </array>
  
  <key>RunAtLoad</key>
  <true/>
  
  <key>WatchPaths</key>
  <array>
    <string>${LOCAL_STATE}</string>
  </array>
  
  <key>StandardOutPath</key>
  <string>${LOG_FILE}</string>
  
  <key>StandardErrorPath</key>
  <string>${LOG_FILE}</string>
</dict>
</plist>
PLIST
  
  ok "LaunchAgent plist created at: $AGENT_PLIST"
}

# ------------------------- Load LaunchAgent -----------------------------------
load_launch_agent() {
  msg "Loading LaunchAgent..."
  
  # Unload if already loaded
  if launchctl list | grep -q "$AGENT_LABEL"; then
    launchctl unload "$AGENT_PLIST" 2>/dev/null || true
  fi
  
  # Load the agent
  if launchctl load "$AGENT_PLIST"; then
    ok "LaunchAgent loaded successfully!"
  else
    err "Failed to load LaunchAgent. Check system logs for details."
    return 1
  fi
}

# ------------------------- Run Initial Patch ----------------------------------
run_initial_patch() {
  msg "Running initial patch..."
  if [[ -f "$PATCHER_SCRIPT" ]]; then
    "$PATCHER_SCRIPT" || warn "Initial patch had some issues (this is okay if Comet hasn't been launched yet)"
    ok "Initial patch complete"
  fi
}

# ----------------------------- Uninstaller ------------------------------------
create_uninstaller() {
  local uninstall_script="${HOME}/Library/Application Support/Complexity/uninstall-comet-patcher.sh"
  
  cat > "$uninstall_script" <<UNINSTALL
#!/usr/bin/env bash
set -euo pipefail

AGENT_LABEL="app.cplx.comet-policy-patcher"
AGENT_PLIST="\${HOME}/Library/LaunchAgents/\${AGENT_LABEL}.plist"
PATCHER_SCRIPT="\${HOME}/Library/Application Support/Complexity/comet-patcher.sh"

echo "Uninstalling Comet Policy Patcher..."

# Unload LaunchAgent
if launchctl list | grep -q "\$AGENT_LABEL"; then
  launchctl unload "\$AGENT_PLIST" 2>/dev/null || true
  echo "✔ LaunchAgent unloaded"
fi

# Remove files
rm -f "\$AGENT_PLIST"
rm -f "\$PATCHER_SCRIPT"
rm -f "\$0"

echo "✔ Uninstallation complete!"
echo ""
echo "Note: Your Comet settings and data remain unchanged."
echo "The Local State backup file (.cplx.bak) is also preserved if you want to restore manually."
UNINSTALL
  
  chmod +x "$uninstall_script"
  ok "Uninstaller created at: $uninstall_script"
}

# ----------------------------- Main -------------------------------------------
main() {
  print_intro
  
  create_patcher_script
  create_launch_agent
  load_launch_agent
  run_initial_patch
  create_uninstaller
  
  printf "\n"
  printf "============================================================\n"
  printf "✅ Installation Complete!\n\n"
  printf "What's next:\n"
  printf "  • Launch Comet normally (no custom shortcut needed!)\n"
  printf "  • The patcher runs automatically in the background\n"
  printf "  • Extensions should work on perplexity.ai domains\n\n"
  printf "Logs: %s\n" "$LOG_FILE"
  printf "To uninstall: bash '%s'\n" "${HOME}/Library/Application Support/Complexity/uninstall-comet-patcher.sh"
  printf "============================================================\n\n"
}

main "$@"
